export const sample_foods = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      price: 10,
      favorite: false,
      stars: 4.5,
      imageUrl: 'food-1.jpg',
    },
    {
      id: '2',
      name: 'Meatball',
      price: 20,
      favorite: true,
      stars: 5,
      imageUrl: 'food-2.jpg',
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 5,
      favorite: false,
      stars: 3.5,
      imageUrl: 'food-3.jpg',
    },
    {
      id: '4',
      name: 'Fried Potatoes',
      price: 2,
      favorite: true,
      stars: 3,
      imageUrl: 'food-4.jpg',
    },
    {
      id: '5',
      name: 'Chicken Soup',
      price: 11,
      favorite: false,
      stars: 3.5,
      imageUrl: 'food-5.jpg',
    },
    {
      id: '6',
      name: 'Vegetables Pizza',
      price: 9,
      favorite: false,
      stars: 4.0,
      imageUrl: 'food-6.jpg',
    },
  ];